version: '3'

services:
  portainer:
    restart: always
    image: portainer/portainer-ce
    container_name: portainer
    command: --admin-password-file=~/portainer-admin-password.txt
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /opt/docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  # ingress:
  #   image: traefik
  #   command: --api.insecure=true --providers.docker
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
    
  # # mdns:
  # #   build: 
  # #     dockerfile: mdns.containerfile
  # #   restart: unless-stopped

  # # whoami:
  # #   image: traefik/whoami
  # #   labels:
  # #     - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"

  # dashboard:
  #   image: lscr.io/linuxserver/heimdall:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8888:80

  # dayboard:
  #   build: 
  #     context: ../dayboard
  #     dockerfile: containerfile
  #   restart: unless-stopped
  #   ports:
  #     - 80

