version: '3'

services:
  ingress:
    container_name: ingress
    image: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

  dashboard:
    container_name: dashboard
    image: lscr.io/linuxserver/heimdall:latest
    restart: unless-stopped
    ports:
      - 8888:80

  dayboard:
    build: 
      context: ../dayboard
      dockerfile: containerfile
    restart: unless-stopped