FROM docker.io/library/python:3

WORKDIR /usr/src/app

# mdns support
RUN apt-get update && apt-get install avahi-utils -y

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./dayboard.py" ]
